### ISSUE TITLE
Cleanup old rows from ddb

### ISSUE THREAD

**Issue by sakibstark11** [CraftsmenLtd/DiscordGems#34]
Since #31, we now have old data in the ddb that needs to be removed. Task is to find a good time to write a script and clean the remaining rows from it.

**Comment by shuaibq3** [comment]
do we need a PR for this? as in, it is a once in a lifetime thing. it may be done from the console, should not take more than 5/10 mins at most i think. anything i am missing here?

**Comment by melon-ruet** [comment]
Well. If someone writes a script, I will vote for not to add with the existing codebase. 
So in a sense it should be a housekeeping issue and int that case a PR is not necessary.
